FROM maven:3.9-eclipse-temurin-17 AS build
WORKDIR /build
COPY pom.xml .
COPY common-models/pom.xml common-models/pom.xml
COPY billing-service/pom.xml billing-service/pom.xml
COPY user-service/pom.xml user-service/pom.xml
COPY order-service/pom.xml order-service/pom.xml
COPY stock-service/pom.xml stock-service/pom.xml
COPY lib lib

RUN mvn -DskipTests -am dependency:go-offline